from fastapi import HTTPException
from models import Users

users = [
    Users(
        id=1,
        name="Leandro",
        surname="Quiriga",
        email="leandro@example.com",
        username="leandroq",
        age=30,
    ),
    Users(
        id=2,
        name="Maria",
        surname="Gomez",
        email="maria@example.com",
        username="mariag",
        age=25,
    ),
    Users(
        id=3,
        name="Carlos",
        surname="Perez",
        email="carlos@example.com",
        username="carlosp",
        age=28,
    ),
    Users(
        id=4,
        name="Ana",
        surname="Lopez",
        email="ana@example.com",
        username="analopez",
        age=22,
    ),
    Users(
        id=5,
        name="Juan",
        surname="Martinez",
        email="juan@example.com",
        username="juanm",
        age=35,
    ),
    Users(
        id=6,
        name="Patricia",
        surname="Garcia",
        email="patricia@example.com",
        username="patriciag",
        age=29,
    ),
    Users(
        id=7,
        name="Roberto",
        surname="Rodriguez",
        email="roberto@example.com",
        username="robertor",
        age=42,
    ),
    Users(
        id=8,
        name="Lucia",
        surname="Sanchez",
        email="lucia@example.com",
        username="lucias",
        age=26,
    ),
    Users(
        id=9,
        name="Diego",
        surname="Fernandez",
        email="diego@example.com",
        username="diegof",
        age=31,
    ),
    Users(
        id=10,
        name="Sofia",
        surname="Torres",
        email="sofia@example.com",
        username="sofiat",
        age=24,
    ),
    Users(
        id=11,
        name="Miguel",
        surname="Ramirez",
        email="miguel@example.com",
        username="miguelr",
        age=38,
    ),
    Users(
        id=12,
        name="Elena",
        surname="Castro",
        email="elena@example.com",
        username="elenac",
        age=27,
    ),
    Users(
        id=13,
        name="Fernando",
        surname="Morales",
        email="fernando@example.com",
        username="fernandom",
        age=33,
    ),
    Users(
        id=14,
        name="Rosa",
        surname="Herrera",
        email="rosa@example.com",
        username="rosah",
        age=30,
    ),
    Users(
        id=15,
        name="Luis",
        surname="Gutierrez",
        email="luis@example.com",
        username="luisg",
        age=36,
    ),
    Users(
        id=16,
        name="Isabel",
        surname="Vargas",
        email="isabel@example.com",
        username="isabelv",
        age=28,
    ),
    Users(
        id=17,
        name="Antonio",
        surname="Medina",
        email="antonio@example.com",
        username="antoniom",
        age=41,
    ),
    Users(
        id=18,
        name="Carmen",
        surname="Flores",
        email="carmen@example.com",
        username="carmenf",
        age=25,
    ),
    Users(
        id=19,
        name="Francisco",
        surname="Ruiz",
        email="francisco@example.com",
        username="franciscor",
        age=39,
    ),
    Users(
        id=20,
        name="Manuela",
        surname="Ortega",
        email="manuela@example.com",
        username="manuelao",
        age=23,
    ),
    Users(
        id=21,
        name="Vicente",
        surname="Dominguez",
        email="vicente@example.com",
        username="vicented",
        age=44,
    ),
    Users(
        id=22,
        name="Dolores",
        surname="Jimenez",
        email="dolores@example.com",
        username="doloresj",
        age=29,
    ),
    Users(
        id=23,
        name="Guillermo",
        surname="Navarro",
        email="guillermo@example.com",
        username="guillermn",
        age=37,
    ),
    Users(
        id=24,
        name="Rosario",
        surname="Vidal",
        email="rosario@example.com",
        username="rosariov",
        age=26,
    ),
]

def search_user(skip: int = 0, limit: int = 10) -> list[Users]:
    # Devuelve una lista de usuarios con paginación
    return users[skip : skip + limit]


def search_user_by_id(id: int) -> Users | None:
    # Busca el usuario con el ID especificado
    user = next((user for user in users if user.id == id), None)
    if user:
        return user  # Devuelve el usuario encontrado
    raise HTTPException(
        status_code=404, detail=f"User {id} not found"
    )  # Devuelve un mensaje si no se encuentra el usuario